Added links to the DX SDKs Community content
pegasystems/react-sdk pull request #105
Opened 2022-07-07 14:39 UTC by syedi2

Added links to relevant SDK Community articles. Corrected the Embedded URL (replaced the /auth.html with /embedded). Made minor updates to improve formatting.

2022-07-07 14:44 UTC, JEAxero requested changes

2022-07-07 14:44 UTC, JEAxero commented on README.md
> +Also, if you ```run npm install``` after it has already been run once, you may see several warnings related to npm peer dependencies that are related to various lint packages. You can ignore these wa
I think only the "npm install" should be in the backticks since the user would type npm install and not run npm install.

2022-07-08 06:00 UTC, syedi2 commented on README.md
> +Also, if you ```run npm install``` after it has already been run once, you may see several warnings related to npm peer dependencies that are related to various lint packages. You can ignore these wa
Yes, brought this up during our chats yesterday. Updated the text.

2022-07-08 12:44 UTC, JEAxero approved these changes

2022-07-08 12:53 UTC, merged