BUG-735131 - Adjust code to try to avoid double slashes for OAuth end…
pegasystems/react-sdk pull request #110
Opened 2022-07-13 04:21 UTC by vrseraphin

…points

2022-07-13 11:45 UTC, JEAxero requested changes
As noted in the failed check. Use of 'var' should be 'let' to satisfy linting.

2022-07-14 03:38 UTC, vrseraphin commented
> As noted in the failed check. Use of 'var' should be 'let' to satisfy linting.

Done

2022-07-14 03:59 UTC, vishalshrm539 approved these changes

2022-07-14 14:44 UTC, JEAxero approved these changes
Ok to merge with the lint fix.

2022-07-14 14:59 UTC, merged