Fixed no records issue in ListView and a style issue
pegasystems/react-sdk pull request #203
Opened 2022-11-29 11:50 UTC by vishalshrm539

* Fixed no records issue in ListView(raised by LeasePlan).
* Please refer BUG-764865 for more details about the issue.

2022-11-29 16:44 UTC, JEAxero requested changes
Ok with me but please think about and address Siva's question to decide which way to do with that.

2022-11-29 16:44 UTC, JEAxero commented on src/components/templates/ListView/index.tsx
> +      payload ? payload.dataViewParameters : dataViewParameters,
Ok. Thanks. In that case, let's put a comment in around line 95 saying that we're using the variable to prepare fr possible upcoming use of a utility function.

2022-11-30 12:52 UTC, vishalshrm539 commented on src/components/templates/ListView/index.tsx
> +      payload ? payload.dataViewParameters : dataViewParameters,
> Ok. Thanks. In that case, let's put a comment in around line 95 saying that we're using the variable to prepare fr possible upcoming use of a utility function.

Added that.

2022-11-30 13:01 UTC, JEAxero approved these changes
Tested and looks good.

2022-11-30 13:58 UTC, merged