Currency using ISO Code and locale
pegasystems/react-sdk pull request #267
Opened 2023-03-15 17:19 UTC by JEAxero

2023-03-17 15:44 UTC, JEAxero commented
Updated branch to detect/fix edge case that Siva had found. Ready for testing again.

2023-03-20 15:02 UTC, tumms2021389 requested changes

2023-03-20 15:02 UTC, tumms2021389 commented on src/components/forms/Currency/currency-utils.ts
> +      }
I feel it's better to move code to line number 39 so that it will handle other unexpected cases.

2023-03-20 15:20 UTC, tumms2021389 approved these changes
Tested, working fine.

2023-03-20 15:47 UTC, merged